version: "3"

services:
  client:
    build: ./client
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - API_URL=http://localhost:3000

  server:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://database:27017/mydb
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
    - ./database:/data/db

